# Source: flux2/templates/helm-controller-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: flux-system/helm-controller
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/part-of: flux
  name: helm-controller
  namespace: flux-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|flux-system|helm-controller'
---
# Source: flux2/templates/source-controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: flux-system/source-controller
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/part-of: flux
  name: source-controller
  namespace: flux-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|flux-system|source-controller'
