# Source: flux2/templates/source-controller-service.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: flux-system/source-controller
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/part-of: flux
    control-plane: controller
  name: source-controller
  namespace: flux-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|flux-system|source-controller'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: source-controller
  type: ClusterIP
